server:
  port: ${server_port}
spring:
  application:
    name: ${application_name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    initialSize: 3
    minIdle: 3
    maxActive: 8
    maxWait: 601000
    timeBetweenEvictionRunsMillis: 601000
    testWhileIdle: true
    validationQuery: select '1'
    testWhileidel: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    asyncInit: false
    filters: stat, wall, log4j2
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    aop:
      auto: true
  redis:
    password: admin
    host: ${redis_host}
    port: ${redis_port}
    database: ${redis_db}
    pool:
      max-wait: 1
      max-idle: 10
      min-idle: 0
    timeout: 0
  data:
    mongodb:
      host: ${mongo_host}
      port: ${mongo_port}
      database: ${mongo_db}
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
logging:
  config: classpath:log4j2.xml
  level: debug
druidUserName: ${druidUserName}
druidUserPassword: ${druidUserPassword}
expire_time: ${expire_time}
shirourl:
  urls:
    /findTest: anon
    /index: anon
    /saveObject: anon
    /findjsonobject: anon
    /**: authc
    /logout: logout
shiro_loginurl: ${shiro_loginurl}
shiro_success: ${shiro_success}
shiro_unauthorizedurl: ${shiro_unauthorizedurl}
